"""Shared constants for the HomeCopy protocol."""

PROTOCOL_VERSION = 1
DEFAULT_MAX_TEXT_LENGTH = 4000
DEFAULT_HISTORY_LIMIT = 50
DEFAULT_RECONNECT_DELAYS = [1, 2, 5, 10]

ERROR_AUTH_FAILED = "AUTH_FAILED"
ERROR_INVALID_MESSAGE = "INVALID_MESSAGE"
ERROR_DEVICE_OFFLINE = "DEVICE_OFFLINE"
ERROR_TEXT_TOO_LONG = "TEXT_TOO_LONG"
ERROR_INTERNAL_ERROR = "INTERNAL_ERROR"
